<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsMaxsysPackage>true</IsMaxsysPackage>
		<Version>0.1.0</Version>
		<Description>Componentes Bootstrap 5.3 para ASP.NET Core MVC: TagHelpers (conteúdo projetado) e ViewComponents (data-driven). (.NET 10)</Description>
		<PackageDescription>Componentes Bootstrap 5.3 para ASP.NET Core MVC: TagHelpers (conteúdo projetado) e ViewComponents (data-driven). (.NET 10)</PackageDescription>
		<PackageId>Maxsys.Bootstrap</PackageId>
		<PackageTags>maxsys;asp-net-mvc;mvc;bootstrap;taghelpers;viewcomponents</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
