<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsMaxsysPackage>true</IsMaxsysPackage>
		<Version>17.0.0</Version>
		<Description>Biblioteca Maxsys para acesso a dados utilizando Entity Framework, Repository Pattern e Unit of Work. (.NET 10)</Description>
		<PackageDescription>Biblioteca Maxsys para acesso a dados utilizando Entity Framework, Repository Pattern e Unit of Work. (.NET 10)</PackageDescription>
		<PackageId>Maxsys.Data</PackageId>
		<PackageTags>maxsys;entity-framework;repository-pattern;unit-of-work</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Maxsys.Core" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Maxsys.Core\Maxsys.Core.csproj" />
	</ItemGroup>

</Project>
