name: .NET + NuGet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pack-push:
    env:
      CAMINHO_PROJETO: ./src/Maxsys.Core/Maxsys.Core.csproj

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # SDK Version to use; x will use the latest version of the 6.0 channel
        include-prerelease: false

    - name: Geração do package
      run: dotnet pack ${{ env.CAMINHO_PROJETO }} -c Release -o out

    - name: Push no NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
