name: .NET + NuGet

on:
  push:
    tags:
      - 'publish-*'
    
jobs:
  pack-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Geração dos packages
      run: dotnet pack src/**/*.csproj -c Release -o out
    
    - name: Publicação no NuGet
      run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
