name: .NET + NuGet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  pack-push:
    env:
      CORE_PATH_PROJ: ./src/Maxsys.Core/Maxsys.Core.csproj
      DATA_PATH_PROJ: ./src/Maxsys.Core.Data/Maxsys.Core.Data.csproj

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # SDK Version to use; x will use the latest version of the 7.0 channel
        include-prerelease: false

    - name: Geração do package Core
      run: dotnet pack ${{ env.CORE_PATH_PROJ }} -c Release -o out

    # - name: Geração do package Data
    #  run: dotnet pack ${{ env.DATA_PATH_PROJ }} -c Release -o out

    - name: Push no NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
